######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 10 23:58:49 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit network

# Input
HEADERS += pagerunner.h nam.h nativeio.h
SOURCES += qtjsruntime.cpp
