option(FILENAME "FILENAME")
FILE(READ "${FILENAME}-" CONTENT)
STRING(REPLACE "IS_COMPILED_CODE = false;" "IS_COMPILED_CODE = true;"
    NEWCONTENT "${CONTENT}")
FILE(WRITE "${FILENAME}" "${NEWCONTENT}")
